In [2]:
# ============================================
#  Module 1 — Dataset Setup & Basic Preprocessing
# ============================================

import pandas as pd
import numpy as np

print(" Loading dataset...")

# ---------- 1. Load the raw dataset ----------
df = pd.read_csv("/Users/ritawang/Desktop/learning/ESE 4170/Final/data/KNN/winequality-red_sep.csv")

# Strip column names to avoid hidden spaces
df.columns = df.columns.str.strip()

print("\n Dataset successfully loaded!")
print("Dataset shape:", df.shape)
print("Columns:", list(df.columns))

# ---------- 2. Basic data integrity check ----------
print("\n Checking for missing values...")
print(df.isnull().sum())

print("\n Summary statistics (first 5 rows):")
display(df.head())

print("\n Descriptive statistics:")
display(df.describe())

# ---------- 3. Extract features & labels ----------
X = df.drop(columns=["quality"])
y = df["quality"]

print("\n Feature matrix shape:", X.shape)
print("Label vector shape:", y.shape)

print("\n Label distribution:")
print(y.value_counts())

print("\n Module 1 Completed — Dataset is ready for modeling in Module 2.")

 Loading dataset...

 Dataset successfully loaded!
Dataset shape: (1599, 12)
Columns: ['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar', 'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol', 'quality']

 Checking for missing values...
fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

 Summary statistics (first 5 rows):

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

 Descriptive statistics:

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
count,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000
mean,8.319637,0.527821,0.270976,2.538806,0.087467,15.874922,46.467792,0.996747,3.311113,0.658149,10.422983,5.636023
std,1.741096,0.179060,0.194801,1.409928,0.047065,10.460157,32.895324,0.001887,0.154386,0.169507,1.065668,0.807569
min,4.600000,0.120000,0.000000,0.900000,0.012000,1.000000,6.000000,0.990070,2.740000,0.330000,8.400000,3.000000
25%,7.100000,0.390000,0.090000,1.900000,0.070000,7.000000,22.000000,0.995600,3.210000,0.550000,9.500000,5.000000
50%,7.900000,0.520000,0.260000,2.200000,0.079000,14.000000,38.000000,0.996750,3.310000,0.620000,10.200000,6.000000
75%,9.200000,0.640000,0.420000,2.600000,0.090000,21.000000,62.000000,0.997835,3.400000,0.730000,11.100000,6.000000
max,15.900000,1.580000,1.000000,15.500000,0.611000,72.000000,289.000000,1.003690,4.010000,2.000000,14.900000,8.000000

 Feature matrix shape: (1599, 11)
Label vector shape: (1599,)

 Label distribution:
quality
5    681
6    638
7    199
4     53
8     18
3     10
Name: count, dtype: int64

 Module 1 Completed — Dataset is ready for modeling in Module 2.

In [3]:
# ============================================
#  Module 2 — Default KNN Baseline (No Scaling, No Tuning)
# ============================================

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print(" Running Module 2: Default KNN Baseline (No Scaling, No Tuning)")

# ---------- 1. Load dataset ----------
df = pd.read_csv("/Users/ritawang/Desktop/learning/ESE 4170/Final/data/KNN/winequality-red_sep.csv")
df.columns = df.columns.str.strip()

X = df.drop(columns=["quality"])
y = df["quality"]

# ---------- 2. Train/Test split (Consistent with all modules) ----------
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("\n Train/Test shapes:", X_train.shape, X_test.shape)

# ---------- 3. Default KNN model ----------
knn_default = KNeighborsClassifier()   # default = n_neighbors=5, metric='minkowski', weights='uniform'

knn_default.fit(X_train, y_train)
y_pred = knn_default.predict(X_test)

# ---------- 4. Evaluation ----------
module2_acc = accuracy_score(y_test, y_pred)

print("\n===============================")
print(" Module 2 — Default KNN Baseline Results")
print("===============================")
print(f"Test Accuracy: {module2_acc:.4f}\n")

print("Classification Report:")
print(classification_report(y_test, y_pred))

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\n Notes:")
print("- Default KNN performs poorly because features are not scaled.")
print("- Hyperparameters are not tuned.")
print("- Wine dataset has mixed units and strong class imbalance.")

# Save baseline results for Module 3
module2_best_params = {
    "n_neighbors": 5,
    "metric": "minkowski",
    "weights": "uniform",
    "p": 2
}

print("\n Saved for later modules:")
print("module2_acc =", module2_acc)
print("module2_best_params =", module2_best_params)

module2_acc

 Running Module 2: Default KNN Baseline (No Scaling, No Tuning)

 Train/Test shapes: (1279, 11) (320, 11)

===============================
 Module 2 — Default KNN Baseline Results
===============================
Test Accuracy: 0.4844

Classification Report:
              precision    recall  f1-score   support

           3       0.00      0.00      0.00         2
           4       0.00      0.00      0.00        11
           5       0.52      0.63      0.57       136
           6       0.48      0.50      0.49       128
           7       0.25      0.12      0.17        40
           8       0.00      0.00      0.00         3

    accuracy                           0.48       320
   macro avg       0.21      0.21      0.20       320
weighted avg       0.44      0.48      0.46       320

Confusion Matrix:
[[ 0  0  1  1  0  0]
 [ 0  0  8  3  0  0]
 [ 0  1 86 45  4  0]
 [ 0  0 55 64  9  0]
 [ 0  0 15 20  5  0]
 [ 0  0  0  1  2  0]]

 Notes:
- Default KNN performs poorly because features are not scaled.
- Hyperparameters are not tuned.
- Wine dataset has mixed units and strong class imbalance.

 Saved for later modules:
module2_acc = 0.484375
module2_best_params = {'n_neighbors': 5, 'metric': 'minkowski', 'weights': 'uniform', 'p': 2}

/opt/anaconda3/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/anaconda3/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/anaconda3/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

0.484375

In [4]:
# ============================================
#  Module 3 — Basic Hyperparameter Tuning
# ============================================

from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV

print("\n==============================")
print(" Module 3 — Basic Hyperparameter Tuning")
print("==============================\n")

# ---------------------------
# 1. Set the parameter adjustment space
# ---------------------------
param_grid = {
    "n_neighbors": [5, 11, 15, 19, 21, 25],
    "weights": ["uniform", "distance"],
    "metric": ["euclidean", "manhattan"]
}

knn = KNeighborsClassifier()

grid = GridSearchCV(
    estimator=knn,
    param_grid=param_grid,
    cv=5,
    scoring="accuracy",
    n_jobs=-1,
    verbose=1
)

print(" Running GridSearchCV...")
grid.fit(X_train, y_train)

# ---------------------------
# 2.Output the best parameters and performance
# ---------------------------
module3_best_params = grid.best_params_
module3_cv_acc = grid.best_score_
module3_test_acc = grid.score(X_test, y_test)

print("\n Best Parameters Found:")
print(module3_best_params)

print(f"\nBest CV Accuracy: {module3_cv_acc:.4f}")
print(f" Test Accuracy AFTER tuning: {module3_test_acc:.4f}")

module3_acc = module3_test_acc

print("\nSaved module3_best_params and module3_acc for Module 4.")

==============================
 Module 3 — Basic Hyperparameter Tuning
==============================

 Running GridSearchCV...
Fitting 5 folds for each of 24 candidates, totalling 120 fits

 Best Parameters Found:
{'metric': 'manhattan', 'n_neighbors': 25, 'weights': 'distance'}

Best CV Accuracy: 0.6223
 Test Accuracy AFTER tuning: 0.6125

Saved module3_best_params and module3_acc for Module 4.

In [5]:
# ============================================
# Module 4 — Advanced Hyperparameter Tuning
# ============================================

from sklearn.model_selection import GridSearchCV

print("\n==============================")
print(" Module 4 — Advanced Hyperparameter Tuning")
print("==============================\n")



try:
    module3_best_params
except NameError:
    raise ValueError(" ERROR: module3_best_params NOT found. Run Module 3 first.")

print("Using best parameters from Module 3:")
print(module3_best_params, "\n")

base_k = module3_best_params["n_neighbors"]

# ---------------------------
# 1.Set the parameter adjustment space
# ---------------------------
param_grid_advanced = {
    "n_neighbors": [
        max(1, base_k - 6),
        base_k - 3,
        base_k,
        base_k + 3,
        base_k + 6
    ],
    "weights": ["uniform", "distance"],
    "metric": ["minkowski", "manhattan", "euclidean"],
    "p": [1, 1.5, 2, 3]  
}

knn_adv = KNeighborsClassifier()

grid_adv = GridSearchCV(
    estimator=knn_adv,
    param_grid=param_grid_advanced,
    cv=5,
    scoring="accuracy",
    n_jobs=-1,
    verbose=1
)

print("Running Advanced GridSearchCV...\n")
grid_adv.fit(X_train, y_train)

# ---------------------------
# 2. Results
# ---------------------------
module4_best_params = grid_adv.best_params_
module4_cv_acc = grid_adv.best_score_
module4_test_acc = grid_adv.score(X_test, y_test)

print("\n Advanced Best Parameters:")
print(module4_best_params)

print(f"\n Module 4 CV Accuracy: {module4_cv_acc:.4f}")
print(f" Module 4 Test Accuracy: {module4_test_acc:.4f}")

module4_acc = module4_test_acc
print("\nSaved module4_acc for next Module.")

==============================
 Module 4 — Advanced Hyperparameter Tuning
==============================

Using best parameters from Module 3:
{'metric': 'manhattan', 'n_neighbors': 25, 'weights': 'distance'}

Running Advanced GridSearchCV...

Fitting 5 folds for each of 120 candidates, totalling 600 fits

 Advanced Best Parameters:
{'metric': 'minkowski', 'n_neighbors': 28, 'p': 1, 'weights': 'distance'}

 Module 4 CV Accuracy: 0.6317
 Module 4 Test Accuracy: 0.6094

Saved module4_acc for next Module.

In [6]:
# ================================
#  Module 5 – StandardScaler Optimization
# ================================

from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.model_selection import cross_val_score, StratifiedKFold
from sklearn.neighbors import KNeighborsClassifier

print("\n===============================")
print(" Module 5 – StandardScaler Optimization")
print("===============================\n")

try:
    best_params_stage4 = module4_best_params
    print("Using module4_best_params from Module 4:")
except NameError:
    best_params_stage4 = module4_best_params
    print("Using advanced_best_params from Module 4 (no module4_best_params found):")

print(best_params_stage4, "\n")

module5_best_params = best_params_stage4.copy()


#  StandardScaler Pipeline
knn_scaled = Pipeline([
    ("scaler", StandardScaler()),
    ("knn", KNeighborsClassifier(
        n_neighbors=best_params_stage4["n_neighbors"],
        metric=best_params_stage4["metric"],
        weights=best_params_stage4["weights"],
        **({"p": best_params_stage4["p"]} if "p" in best_params_stage4 else {})
    ))
])

#  5-Fold Stratified CV
cv5 = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
cv_scores_m5 = cross_val_score(knn_scaled, X_train, y_train, cv=cv5)

module5_cv_acc = cv_scores_m5.mean()

print(" Module 5 CV Accuracy (with StandardScaler): {:.4f}".format(module5_cv_acc))
print("CV scores by fold:", cv_scores_m5, "\n")

# 4. TEST 
knn_scaled.fit(X_train, y_train)
y_test_pred_m5 = knn_scaled.predict(X_test)

module5_acc = accuracy_score(y_test, y_test_pred_m5)

print(" Module 5 Test Accuracy (with StandardScaler): {:.4f}".format(module5_acc))
print("\nClassification Report (Module 5):")
print(classification_report(y_test, y_test_pred_m5))
print("Confusion Matrix (Module 5):")
print(confusion_matrix(y_test, y_test_pred_m5))

# 5.Comparsion
try:
    print("\n=== Comparison with Module 4 ===")
    print("Module 4 Test Accuracy:", module4_acc)
    print("Module 5 Test Accuracy:", module5_acc)
    if module5_acc > module4_acc:
        print(" StandardScaler improved performance!")
    elif module5_acc < module4_acc:
        print(" Performance dropped slightly with StandardScaler.")
    else:
        print("ℹ No significant change.")
except NameError:
    print("\n( module4_acc not found, cannot compare automatically.)")


print("\nSaving key results for Module 6...")

saved_module5_acc = module5_acc
saved_module5_best_params = module5_best_params

print("✔ saved_module5_acc =", saved_module5_acc)
print("✔ saved_module5_best_params =", saved_module5_best_params)

===============================
 Module 5 – StandardScaler Optimization
===============================

Using module4_best_params from Module 4:
{'metric': 'minkowski', 'n_neighbors': 28, 'p': 1, 'weights': 'distance'}

 Module 5 CV Accuracy (with StandardScaler): 0.6669
CV scores by fold: [0.65234375 0.68359375 0.69921875 0.640625   0.65882353]

 Module 5 Test Accuracy (with StandardScaler): 0.6562

Classification Report (Module 5):
              precision    recall  f1-score   support

           3       0.00      0.00      0.00         2
           4       0.00      0.00      0.00        11
           5       0.72      0.71      0.72       136
           6       0.59      0.72      0.65       128
           7       0.69      0.50      0.58        40
           8       1.00      0.33      0.50         3

    accuracy                           0.66       320
   macro avg       0.50      0.38      0.41       320
weighted avg       0.64      0.66      0.64       320

Confusion Matrix (Module 5):
[[ 0  0  1  1  0  0]
 [ 0  0  7  4  0  0]
 [ 0  0 97 38  1  0]
 [ 0  0 28 92  8  0]
 [ 0  0  1 19 20  0]
 [ 0  0  0  2  0  1]]

=== Comparison with Module 4 ===
Module 4 Test Accuracy: 0.609375
Module 5 Test Accuracy: 0.65625
 StandardScaler improved performance!

Saving key results for Module 6...
✔ saved_module5_acc = 0.65625
✔ saved_module5_best_params = {'metric': 'minkowski', 'n_neighbors': 28, 'p': 1, 'weights': 'distance'}

/opt/anaconda3/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/anaconda3/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/anaconda3/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [7]:
# ================================
#  Module 6 – Feature Selection (SelectKBest)
# ================================

from sklearn.feature_selection import SelectKBest, f_classif
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.model_selection import StratifiedKFold, cross_val_score
from sklearn.neighbors import KNeighborsClassifier

print("\n===============================")
print(" Module 6 – Feature Selection Optimization")
print("===============================\n")

best_params_stage5 = module4_best_params  
print("Using previous best KNN parameters:")
print(best_params_stage5, "\n")

# k
k_values = [3, 4, 5, 6, 7, 8]

results = []

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

for k in k_values:
    pipe = Pipeline([
        ("scaler", StandardScaler()),
        ("select", SelectKBest(f_classif, k=k)),
        ("knn", KNeighborsClassifier(
            n_neighbors=best_params_stage5["n_neighbors"],
            metric=best_params_stage5["metric"],
            weights=best_params_stage5["weights"],
            **({"p": best_params_stage5["p"]} if "p" in best_params_stage5 else {})
        ))
    ])

    cv_score = cross_val_score(pipe, X_train, y_train, cv=cv).mean()
    results.append((k, cv_score))

# cv-k
print("CV Accuracy for different K best feature numbers:")
for k, score in results:
    print(f"  k = {k}:  CV = {score:.4f}")

# best k
best_k, best_k_cv = max(results, key=lambda x: x[1])
print("\n Best k found:", best_k)
print(" Best CV accuracy with SelectKBest:", best_k_cv)

#retrain
final_pipe = Pipeline([
    ("scaler", StandardScaler()),
    ("select", SelectKBest(f_classif, k=best_k)),
    ("knn", KNeighborsClassifier(
        n_neighbors=best_params_stage5["n_neighbors"],
        metric=best_params_stage5["metric"],
        weights=best_params_stage5["weights"],
        **({"p": best_params_stage5["p"]} if "p" in best_params_stage5 else {})
    ))
])

final_pipe.fit(X_train, y_train)
y_pred_m6 = final_pipe.predict(X_test)

module6_acc = accuracy_score(y_test, y_pred_m6)

print("\n Module 6 Test Accuracy:", module6_acc)
print("\nClassification Report (Module 6):")
print(classification_report(y_test, y_pred_m6))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_m6))

# comparsion
print("\n===== Comparison with Module 5 =====")
print(f"Module 5 Test Accuracy: {module5_acc:.4f}")
print(f"Module 6 Test Accuracy: {module6_acc:.4f}")

if module6_acc > module5_acc:
    print("\n Feature Selection IMPROVED generalization. Keep as valid optimization.")
else:
    print("\n Feature Selection did NOT improve accuracy. Should be REJECTED in final report.")


module6_best_k = best_k
module6_acc = module6_acc
best_model_stage6 = final_pipe

print("\nSaved module6_acc =", module6_acc)
print("Selected features (k) =", best_k)



# 使用 Module 6 的最佳特征数量 k=6
selector = SelectKBest(score_func=f_classif, k=6)
selector.fit(X_train, y_train)

selected_mask = selector.get_support()
selected_features = X_train.columns[selected_mask]

print("👉 Selected features by SelectKBest (k=6):")
print(list(selected_features))

===============================
 Module 6 – Feature Selection Optimization
===============================

Using previous best KNN parameters:
{'metric': 'minkowski', 'n_neighbors': 28, 'p': 1, 'weights': 'distance'}

CV Accuracy for different K best feature numbers:
  k = 3:  CV = 0.6599
  k = 4:  CV = 0.6834
  k = 5:  CV = 0.6755
  k = 6:  CV = 0.6880
  k = 7:  CV = 0.6771
  k = 8:  CV = 0.6724

 Best k found: 6
 Best CV accuracy with SelectKBest: 0.6880269607843138

 Module 6 Test Accuracy: 0.65

Classification Report (Module 6):
              precision    recall  f1-score   support

           3       0.00      0.00      0.00         2
           4       0.00      0.00      0.00        11
           5       0.69      0.71      0.70       136
           6       0.59      0.70      0.64       128
           7       0.75      0.53      0.62        40
           8       1.00      0.33      0.50         3

    accuracy                           0.65       320
   macro avg       0.51      0.38      0.41       320
weighted avg       0.63      0.65      0.64       320

Confusion Matrix:
[[ 0  0  1  1  0  0]
 [ 0  0  8  3  0  0]
 [ 0  0 97 39  0  0]
 [ 0  0 33 89  6  0]
 [ 0  0  1 18 21  0]
 [ 0  0  0  1  1  1]]

===== Comparison with Module 5 =====
Module 5 Test Accuracy: 0.6562
Module 6 Test Accuracy: 0.6500

 Feature Selection did NOT improve accuracy. Should be REJECTED in final report.

Saved module6_acc = 0.65
Selected features (k) = 6
👉 Selected features by SelectKBest (k=6):
['volatile acidity', 'citric acid', 'total sulfur dioxide', 'density', 'sulphates', 'alcohol']

/opt/anaconda3/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/anaconda3/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/anaconda3/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [8]:
# ============================================
#  Module 7 — PCA Feature Expansion Optimization
#      (based on Module 5 best model)
# ============================================

from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.model_selection import cross_val_score, train_test_split
from sklearn.neighbors import KNeighborsClassifier
import numpy as np
import pandas as pd

print("\n============================================")
print("Module 7 — PCA Feature Expansion Optimization")
print("============================================\n")

print("Using best KNN parameters from Module 5:")
print(module5_best_params, "\n")
print(f"Module 5 Test Accuracy (baseline): {module5_acc:.4f}\n")

df = pd.read_csv("/Users/ritawang/Desktop/learning/ESE 4170/Final/data/KNN/winequality-red_sep.csv")
df.columns = df.columns.str.strip()

X = df.drop(columns=["quality"])
y = df["quality"]

# 3. Standardization (in the same way as Module 5
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# 4.Generate two principal components of PCA as "new features"
pca = PCA(n_components=2, random_state=42)
X_pca = pca.fit_transform(X_scaled)

print("Explained variance ratio (PC1, PC2):", pca.explained_variance_ratio_, "\n")

# Piece the PCA features back to the original features (expand dimension, not reduce dimension)
df_pca = pd.DataFrame(X_pca, columns=["PC1", "PC2"])
X_expanded = pd.concat([X.reset_index(drop=True), df_pca], axis=1)

print("Original feature count:", X.shape[1])
print("New feature count after PCA expansion:", X_expanded.shape[1], "\n")

# 5. Build the KNN using the optimal parameters of Module 5
knn7 = KNeighborsClassifier(
    n_neighbors=module5_best_params["n_neighbors"],
    weights=module5_best_params["weights"],
    metric=module5_best_params["metric"],
    p=module5_best_params.get("p", 2)  
)

# 6. cv
cv_scores = cross_val_score(knn7, X_expanded, y, cv=5)
module7_cv = cv_scores.mean()

print(f"⭐ Module 7 CV Accuracy (with PCA expansion): {module7_cv:.4f}")
print("CV scores by fold:", cv_scores, "\n")

# 7.  Train/Test 
X_train, X_test, y_train, y_test = train_test_split(
    X_expanded, y, test_size=0.2, random_state=42, stratify=y
)

knn7.fit(X_train, y_train)
test_acc7 = knn7.score(X_test, y_test)

print(f" Module 7 Test Accuracy (with PCA expansion): {test_acc7:.4f}\n")

# 8. Comparsion
print(" Comparison with Module 5 baseline:")
print(f"  • Module 5 Test Accuracy: {module5_acc:.4f}")
print(f"  • Module 7 Test Accuracy: {test_acc7:.4f}\n")

if test_acc7 > module5_acc:
    print(" PCA dimensionality expansion enhances generalization ability, and this step can be marked as SUCCESSFUL optimization in the final report.")
else:
    print(" PCA dimensionality expansion did not bring about improvement. It can be attempted in the final report but is marked as REJECTED.")
    print(" The subsequent modules will continue to take Module 5 as the baseline.\n")

module7_acc = test_acc7          #  Test Accuracy
module7_best_params = module5_best_params  

print("Saved module7_acc =", module7_acc)

============================================
Module 7 — PCA Feature Expansion Optimization
============================================

Using best KNN parameters from Module 5:
{'metric': 'minkowski', 'n_neighbors': 28, 'p': 1, 'weights': 'distance'}

Module 5 Test Accuracy (baseline): 0.6562

Explained variance ratio (PC1, PC2): [0.28173931 0.1750827 ]

Original feature count: 11
New feature count after PCA expansion: 13

⭐ Module 7 CV Accuracy (with PCA expansion): 0.5247
CV scores by fold: [0.571875  0.521875  0.521875  0.50625   0.5015674]

 Module 7 Test Accuracy (with PCA expansion): 0.6531

 Comparison with Module 5 baseline:
  • Module 5 Test Accuracy: 0.6562
  • Module 7 Test Accuracy: 0.6531

 PCA dimensionality expansion did not bring about improvement. It can be attempted in the final report but is marked as REJECTED.
 The subsequent modules will continue to take Module 5 as the baseline.

Saved module7_acc = 0.653125

In [9]:
# ================================
#  Module 8 – Mutual Information (MI) Feature Selection (非线性特征筛选)
# ================================

from sklearn.feature_selection import SelectKBest, mutual_info_classif
from sklearn.pipeline import Pipeline
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import StratifiedKFold, cross_val_score
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print("\n===============================")
print(" Module 8 – Mutual Information (MI) Feature Selection")
print("===============================\n")

# ------------------------------------------------------
# 1.  Module 5 
# ------------------------------------------------------
try:
    base_params = best_params_stage5
    print("Using best KNN parameters from Module 5:")
except:
    base_params = best_params_stage4
    print("⚠️ Module 5 best params not found. Falling back to Module 4 parameters:")

print(base_params, "\n")

# ------------------------------------------------------
# 2.  top-k 
# ------------------------------------------------------
k_values = [3, 4, 5, 6, 7, 8, 9, 10]  
cv_results = {}
cv5 = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

print("CV Accuracy for different k (number of MI-selected features):\n")

for k in k_values:
    pipe = Pipeline([
        ("selector", SelectKBest(mutual_info_classif, k=k)),
        ("knn", KNeighborsClassifier(
            n_neighbors=base_params["n_neighbors"],
            metric=base_params["metric"],
            weights=base_params["weights"],
            **({"p": base_params["p"]} if "p" in base_params else {})
        ))
    ])

    scores = cross_val_score(pipe, X_train, y_train, cv=cv5)
    cv_results[k] = scores.mean()
    print(f"  k = {k}:  CV = {scores.mean():.4f}")

# ------------------------------------------------------
# 3.  k
# ------------------------------------------------------
best_k_mi = max(cv_results, key=cv_results.get)
best_cv_mi = cv_results[best_k_mi]

print("\n⭐ Best k selected by MI:", best_k_mi)
print("⭐ Best CV Accuracy:", best_cv_mi)

# ------------------------------------------------------
# 4.  test accuracy
# ------------------------------------------------------
final_model_mi = Pipeline([
    ("selector", SelectKBest(mutual_info_classif, k=best_k_mi)),
    ("knn", KNeighborsClassifier(
        n_neighbors=base_params["n_neighbors"],
        metric=base_params["metric"],
        weights=base_params["weights"],
        **({"p": base_params["p"]} if "p" in base_params else {})
    ))
])

final_model_mi.fit(X_train, y_train)
y_pred_m8 = final_model_mi.predict(X_test)

module8_acc = accuracy_score(y_test, y_pred_m8)

print("\n⭐ Module 8 Test Accuracy:", module8_acc)
print("\nClassification Report (Module 8):")
print(classification_report(y_test, y_pred_m8))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_m8))

# ------------------------------------------------------
# 5.  Module 5 baseline -compare
# ------------------------------------------------------
print("\n Comparison with Module 5 baseline:")
print("  • Module 5 Test Accuracy:", module5_acc)
print("  • Module 8 Test Accuracy:", module8_acc)

if module8_acc > module5_acc:
    print("\n MI-based Feature Selection IMPROVED accuracy → KEEP this module.")
else:
    print("\n MI Selection did NOT improve accuracy → REJECT this module in final report.")


module8_acc = module8_acc
best_model_stage8 = final_model_mi

print("\nSaved module8_acc =", module8_acc)
print("Selected MI top-k features =", best_k_mi)

===============================
 Module 8 – Mutual Information (MI) Feature Selection
===============================

Using best KNN parameters from Module 5:
{'metric': 'minkowski', 'n_neighbors': 28, 'p': 1, 'weights': 'distance'}

CV Accuracy for different k (number of MI-selected features):

  k = 3:  CV = 0.6443
  k = 4:  CV = 0.6544
  k = 5:  CV = 0.6615
  k = 6:  CV = 0.6403
  k = 7:  CV = 0.6310
  k = 8:  CV = 0.6302
  k = 9:  CV = 0.6325
  k = 10:  CV = 0.6271

⭐ Best k selected by MI: 5
⭐ Best CV Accuracy: 0.661467524509804

⭐ Module 8 Test Accuracy: 0.671875

Classification Report (Module 8):
              precision    recall  f1-score   support

           3       0.00      0.00      0.00         2
           4       0.00      0.00      0.00        11
           5       0.71      0.73      0.72       136
           6       0.62      0.73      0.67       128
           7       0.73      0.55      0.63        40
           8       0.50      0.33      0.40         3

    accuracy                           0.67       320
   macro avg       0.43      0.39      0.40       320
weighted avg       0.65      0.67      0.66       320

Confusion Matrix:
[[ 0  0  2  0  0  0]
 [ 0  0  7  4  0  0]
 [ 0  0 99 34  3  0]
 [ 0  0 30 93  5  0]
 [ 0  0  1 16 22  1]
 [ 0  0  0  2  0  1]]

 Comparison with Module 5 baseline:
  • Module 5 Test Accuracy: 0.65625
  • Module 8 Test Accuracy: 0.671875

 MI-based Feature Selection IMPROVED accuracy → KEEP this module.

Saved module8_acc = 0.671875
Selected MI top-k features = 5

/opt/anaconda3/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/anaconda3/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/anaconda3/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [10]:
# ================================
#  Module 9 – Polynomial Feature Expansion (degree=2)
# ================================

from sklearn.preprocessing import PolynomialFeatures, StandardScaler
from sklearn.feature_selection import SelectKBest, f_classif
from sklearn.pipeline import Pipeline
from sklearn.model_selection import StratifiedKFold, cross_val_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print("\n===============================")
print(" Module 9 – Polynomial Feature Expansion (degree=2)")
print("===============================\n")


try:
    best_params = module5_best_params 
    print("Using KNN parameters from Module 5:")
except NameError:
    best_params = best_params_stage5   
    print("Fallback: Using parameters from best_params_stage5:")
    
print(best_params, "\n")

baseline_acc = module5_acc
print(f"Module 5 baseline Test Accuracy: {baseline_acc:.4f}\n")

# ===========================================
# 2️Testing PolynomialFeatures + SelectKBest
# ===========================================

poly_knn_results = {}

print("🔍 Testing PolynomialFeatures + SelectKBest for different k values...\n")

for k in [10, 15, 20, 25, 30, 35, 40]:
    pipe = Pipeline([
        ("poly", PolynomialFeatures(degree=2, include_bias=False)),
        ("scaler", StandardScaler()),
        ("select", SelectKBest(score_func=f_classif, k=k)),
        ("knn", KNeighborsClassifier(
            n_neighbors=best_params["n_neighbors"],
            metric=best_params["metric"],
            weights=best_params["weights"],
            **({"p": best_params["p"]} if "p" in best_params else {})
        ))
    ])

    cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
    cv_scores = cross_val_score(pipe, X_train, y_train, cv=cv)

    poly_knn_results[k] = cv_scores.mean()
    print(f"k = {k}: CV Accuracy = {cv_scores.mean():.4f}")

# ===========================================
#  k
# ===========================================

best_k_poly = max(poly_knn_results, key=poly_knn_results.get)
best_cv_poly = poly_knn_results[best_k_poly]

print("\n Best k selected for PolynomialFeatures:", best_k_poly)
print(f" Best CV Accuracy (PolynomialFeatures): {best_cv_poly:.4f}\n")

# ===========================================
#  Test 
# ===========================================

final_poly_model = Pipeline([
    ("poly", PolynomialFeatures(degree=2, include_bias=False)),
    ("scaler", StandardScaler()),
    ("select", SelectKBest(score_func=f_classif, k=best_k_poly)),
    ("knn", KNeighborsClassifier(
        n_neighbors=best_params["n_neighbors"],
        metric=best_params["metric"],
        weights=best_params["weights"],
        **({"p": best_params["p"]} if "p" in best_params else {})
    ))
])

final_poly_model.fit(X_train, y_train)
y_test_pred_poly = final_poly_model.predict(X_test)

module9_acc = accuracy_score(y_test, y_test_pred_poly)

print(" Module 9 Test Accuracy:", module9_acc)
print("\nClassification Report (Module 9):")
print(classification_report(y_test, y_test_pred_poly))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_test_pred_poly))

# ===========================================
# compare Module 5 baseline 
# ===========================================

print("\n===============================")
print(" Comparison with Module 5 baseline")
print("===============================\n")
print(f"Module 5 Test Accuracy: {baseline_acc:.4f}")
print(f"Module 9 Test Accuracy: {module9_acc:.4f}")

if module9_acc > baseline_acc:
    print(" Polynomial Feature Expansion SUCCESSFULLY improved KNN performance!")
else:
    print(" Polynomial Feature Expansion did NOT improve accuracy → REJECT in final report.")



module9_best_params = best_params   
module9_best_k = best_k_poly  
module9_acc = module9_acc

print("\nSaved module9_best_params =", module9_best_params)
print("Saved module9_best_k =", module9_best_k)
print("Saved module9_acc =", module9_acc)

===============================
 Module 9 – Polynomial Feature Expansion (degree=2)
===============================

Using KNN parameters from Module 5:
{'metric': 'minkowski', 'n_neighbors': 28, 'p': 1, 'weights': 'distance'}

Module 5 baseline Test Accuracy: 0.6562

🔍 Testing PolynomialFeatures + SelectKBest for different k values...

k = 10: CV Accuracy = 0.6568
k = 15: CV Accuracy = 0.6716
k = 20: CV Accuracy = 0.6708
k = 25: CV Accuracy = 0.6693
k = 30: CV Accuracy = 0.6615
k = 35: CV Accuracy = 0.6732
k = 40: CV Accuracy = 0.6654

 Best k selected for PolynomialFeatures: 35
 Best CV Accuracy (PolynomialFeatures): 0.6732

 Module 9 Test Accuracy: 0.665625

Classification Report (Module 9):
              precision    recall  f1-score   support

           3       0.00      0.00      0.00         2
           4       0.00      0.00      0.00        11
           5       0.72      0.74      0.73       136
           6       0.61      0.71      0.66       128
           7       0.66      0.53      0.58        40
           8       1.00      0.33      0.50         3

    accuracy                           0.67       320
   macro avg       0.50      0.38      0.41       320
weighted avg       0.64      0.67      0.65       320

Confusion Matrix:
[[  0   0   1   1   0   0]
 [  0   0   9   2   0   0]
 [  0   0 100  35   1   0]
 [  0   0  28  91   9   0]
 [  0   0   1  18  21   0]
 [  0   0   0   1   1   1]]

===============================
 Comparison with Module 5 baseline
===============================

Module 5 Test Accuracy: 0.6562
Module 9 Test Accuracy: 0.6656
 Polynomial Feature Expansion SUCCESSFULLY improved KNN performance!

Saved module9_best_params = {'metric': 'minkowski', 'n_neighbors': 28, 'p': 1, 'weights': 'distance'}
Saved module9_best_k = 35
Saved module9_acc = 0.665625

/opt/anaconda3/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/anaconda3/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/anaconda3/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [11]:
# ================================
#  Module 10 – Feature Weighting Optimization
# ================================

from sklearn.feature_selection import f_classif
from sklearn.preprocessing import MinMaxScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.model_selection import StratifiedKFold, cross_val_score
import numpy as np

print("\n===============================")
print("Module 10 – Feature Weighting Optimization")
print("===============================\n")

try:
    best_params_m9 = {
        "metric": best_params_stage5["metric"],
        "n_neighbors": module9_best_k,
        "weights": best_params_stage5["weights"],
        "p": best_params_stage5["p"]
    }
except:
    best_params_m9 = {"metric": "minkowski", "n_neighbors": 28, "weights": "distance", "p": 1}

print("Using KNN parameters from Module 9:")
print(best_params_m9, "\n")

# ---------------------------------------------------------
#  F-score
# ---------------------------------------------------------
F_values, p_values = f_classif(X_train, y_train)

weights = np.clip(F_values, a_min=0, a_max=None)
weights = weights / weights.max()

print("Raw F-score values:\n", F_values)
print("\nNormalized feature weights:\n", weights, "\n")

# ---------------------------------------------------------
# 3️Define the weighted distance function (based on Euclidean distance)
# ---------------------------------------------------------

def weighted_distance(x, y):
    return np.sqrt(np.sum(weights * (x - y)**2))

# sklearn 允许将 metric 传入自定义函数
def weighted_metric(a, b):
    return weighted_distance(a, b)

# ---------------------------------------------------------
# weighted distance - KNN
# ---------------------------------------------------------
knn_weighted = KNeighborsClassifier(
    n_neighbors=best_params_m9["n_neighbors"],
    metric=weighted_metric
)

# ---------------------------------------------------------
#  5-fold CV
# ---------------------------------------------------------
cv10 = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
cv_scores_m10 = cross_val_score(knn_weighted, X_train, y_train, cv=cv10)

module10_cv_acc = cv_scores_m10.mean()

print("⭐ Module 10 CV Accuracy (weighted KNN): {:.4f}".format(module10_cv_acc))
print("CV scores by fold:", cv_scores_m10, "\n")

# ---------------------------------------------------------
#  Fit + Test Accuracy
# ---------------------------------------------------------
knn_weighted.fit(X_train, y_train)
y_test_pred_m10 = knn_weighted.predict(X_test)

module10_acc = accuracy_score(y_test, y_test_pred_m10)

print("⭐ Module 10 Test Accuracy:", module10_acc)
print("\nClassification Report (Module 10):")
print(classification_report(y_test, y_test_pred_m10))
print("Confusion Matrix (Module 10):")
print(confusion_matrix(y_test, y_test_pred_m10))

# ---------------------------------------------------------
# Compare with Module 9 baseline 
# ---------------------------------------------------------
print("\n=== Comparison with Module 9 baseline ===")
print("Module 9 Test Accuracy:", module9_acc)
print("Module 10 Test Accuracy:", module10_acc)

if module10_acc > module9_acc:
    print(" Feature Weighting SUCCESSFULLY improved model performance!")
    result_m10 = "ACCEPTED"
elif module10_acc == module9_acc:
    print(" Feature Weighting produced SAME performance as Module 9.")
    result_m10 = "NEUTRAL"
else:
    print(" Feature Weighting REDUCED performance → REJECT this module.")
    result_m10 = "REJECTED"


module10_result = {
    "cv_acc": module10_cv_acc,
    "test_acc": module10_acc,
    "weights": weights,
    "status": result_m10
}

print("\nSaved module10_result =", module10_result)

===============================
Module 10 – Feature Weighting Optimization
===============================

Using KNN parameters from Module 9:
{'metric': 'minkowski', 'n_neighbors': 35, 'weights': 'distance', 'p': 1}

Raw F-score values:
 [ 4.13588948 48.71399369 13.56993225  1.34163501  4.21621774  4.83624968
 22.39846224 13.27937287  3.10620611 14.56212524 97.16300207  4.25357227
 58.21528261]

Normalized feature weights:
 [0.04256651 0.50136361 0.13966152 0.01380809 0.04339324 0.0497746
 0.2305246  0.13667108 0.03196902 0.14987315 1.         0.0437777
 0.59915072]

⭐ Module 10 CV Accuracy (weighted KNN): 0.5473
CV scores by fold: [0.53125    0.53125    0.5859375  0.53125    0.55686275]

⭐ Module 10 Test Accuracy: 0.553125

Classification Report (Module 10):
              precision    recall  f1-score   support

           3       0.00      0.00      0.00         2
           4       0.00      0.00      0.00        11
           5       0.59      0.73      0.65       136
           6       0.52      0.58      0.55       128
           7       0.40      0.10      0.16        40
           8       0.00      0.00      0.00         3

    accuracy                           0.55       320
   macro avg       0.25      0.23      0.23       320
weighted avg       0.51      0.55      0.52       320

Confusion Matrix (Module 10):
[[ 0  0  2  0  0  0]
 [ 0  0  8  3  0  0]
 [ 0  0 99 35  2  0]
 [ 0  0 51 74  3  0]
 [ 0  0  7 29  4  0]
 [ 0  0  0  2  1  0]]

=== Comparison with Module 9 baseline ===
Module 9 Test Accuracy: 0.665625
Module 10 Test Accuracy: 0.553125
 Feature Weighting REDUCED performance → REJECT this module.

Saved module10_result = {'cv_acc': np.float64(0.5473100490196078), 'test_acc': 0.553125, 'weights': array([0.04256651, 0.50136361, 0.13966152, 0.01380809, 0.04339324,
       0.0497746 , 0.2305246 , 0.13667108, 0.03196902, 0.14987315,
       1.        , 0.0437777 , 0.59915072]), 'status': 'REJECTED'}

/opt/anaconda3/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/anaconda3/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/anaconda3/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [12]:
# ==============================================
#  Module 11 – Noise Cleaning (NCR) Optimization
# ==============================================
from imblearn.under_sampling import NeighbourhoodCleaningRule
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import cross_val_score, StratifiedKFold
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print("\n=====================================")
print(" Module 11 – Noise Cleaning (NCR)")
print("=====================================\n")

try:
    print("Using best KNN parameters from Module 9:")
    print(module9_best_params, "\n")
    params_m11 = module9_best_params
except:
    print("Using manual fallback parameters (Module 9 not loaded).")
    params_m11 = {"n_neighbors": 35, "metric": "minkowski", "p": 1, "weights": "distance"}

baseline_acc = module9_acc  
print(f"Module 9 baseline Test Accuracy: {baseline_acc:.4f}\n")

print(" Applying Neighbourhood Cleaning Rule (NCR)...")

ncr = NeighbourhoodCleaningRule(n_neighbors=3)

X_train_cleaned, y_train_cleaned = ncr.fit_resample(X_train, y_train)

print(f"Original training size: {len(y_train)}")
print(f"Cleaned training size:  {len(y_train_cleaned)}")
print("\nClass distribution after NCR:")
print(y_train_cleaned.value_counts(), "\n")

knn_ncr = Pipeline([
    ("scaler", StandardScaler()),
    ("knn", KNeighborsClassifier(
        n_neighbors=params_m11["n_neighbors"],
        metric=params_m11["metric"],
        weights=params_m11["weights"],
        **({"p": params_m11["p"]} if "p" in params_m11 else {})
    ))
])

# ---------------------------
# 5-Fold CV on cleaned data
# ---------------------------
cv5 = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
cv_scores_m11 = cross_val_score(knn_ncr, X_train_cleaned, y_train_cleaned, cv=cv5)

module11_cv_acc = cv_scores_m11.mean()
print(f"⭐ Module 11 CV Accuracy (after NCR): {module11_cv_acc:.4f}")
print("CV scores:", cv_scores_m11, "\n")

# ---------------------------
#  Test set evaluation
# ---------------------------
knn_ncr.fit(X_train_cleaned, y_train_cleaned)
y_test_pred_m11 = knn_ncr.predict(X_test)

module11_acc = accuracy_score(y_test, y_test_pred_m11)

print(f" Module 11 Test Accuracy: {module11_acc:.4f}\n")
print("Classification Report (Module 11):")
print(classification_report(y_test, y_test_pred_m11))
print("Confusion Matrix (Module 11):")
print(confusion_matrix(y_test, y_test_pred_m11), "\n")


print(" Comparison with Module 9 baseline:")
print(f"Module 9 Test Accuracy: {baseline_acc:.4f}")
print(f"Module 11 Test Accuracy: {module11_acc:.4f}")

if module11_acc > baseline_acc:
    print(" NCR SUCCESSFULLY improved generalization! Keep this module.")
    module11_status = "ACCEPTED"
else:
    print(" NCR did NOT improve accuracy → REJECT this module.")
    module11_status = "REJECTED"

module11_result = {
    "cv_acc": module11_cv_acc,
    "test_acc": module11_acc,
    "status": module11_status,
    "cleaned_size": len(y_train_cleaned)
}

print("\nSaved module11_result =", module11_result)

=====================================
 Module 11 – Noise Cleaning (NCR)
=====================================

Using best KNN parameters from Module 9:
{'metric': 'minkowski', 'n_neighbors': 28, 'p': 1, 'weights': 'distance'}

Module 9 baseline Test Accuracy: 0.6656

 Applying Neighbourhood Cleaning Rule (NCR)...
Original training size: 1279
Cleaned training size:  611

Class distribution after NCR:
quality
5    347
6    211
7     44
3      8
4      1
Name: count, dtype: int64

⭐ Module 11 CV Accuracy (after NCR): 0.8248
CV scores: [0.86178862 0.86065574 0.82786885 0.75409836 0.81967213]

 Module 11 Test Accuracy: 0.5813

Classification Report (Module 11):
              precision    recall  f1-score   support

           3       0.00      0.00      0.00         2
           4       0.00      0.00      0.00        11
           5       0.64      0.72      0.68       136
           6       0.52      0.62      0.57       128
           7       0.57      0.20      0.30        40
           8       0.00      0.00      0.00         3

    accuracy                           0.58       320
   macro avg       0.29      0.26      0.26       320
weighted avg       0.55      0.58      0.55       320

Confusion Matrix (Module 11):
[[ 0  0  1  1  0  0]
 [ 0  0  9  2  0  0]
 [ 0  0 98 37  1  0]
 [ 0  0 43 80  5  0]
 [ 0  0  2 30  8  0]
 [ 0  0  0  3  0  0]]

 Comparison with Module 9 baseline:
Module 9 Test Accuracy: 0.6656
Module 11 Test Accuracy: 0.5813
 NCR did NOT improve accuracy → REJECT this module.

Saved module11_result = {'cv_acc': np.float64(0.8248167399706784), 'test_acc': 0.58125, 'status': 'REJECTED', 'cleaned_size': 611}

/opt/anaconda3/lib/python3.13/site-packages/sklearn/model_selection/_split.py:805: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(
/opt/anaconda3/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/anaconda3/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/anaconda3/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [13]:
# ================================
#  Module 12 – Multi-K Resampled Ensemble KNN
# ================================

from sklearn.ensemble import BaggingClassifier, VotingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

print("\n===============================")
print(" Module 12 – Multi-K Resampled Ensemble KNN")
print("===============================\n")

base_params = module9_best_params
print("Using base parameters from Module 9:")
print(base_params, "\n")

p_val = base_params.get("p", 2)

K_list = [15, 25, 35, 45]
print("Multi-K ensemble will use K values:", K_list, "\n")

estimators = []

for k in K_list:
    knn = KNeighborsClassifier(
        n_neighbors=k,
        metric=base_params["metric"],
        p=p_val,
        weights=base_params["weights"]
    )

    bagged_knn = BaggingClassifier(
        estimator=knn,
        n_estimators=15,
        max_samples=0.8,
        bootstrap=True,
        random_state=42,
        n_jobs=-1
    )

    pipe = Pipeline([
        ("scaler", StandardScaler()),
        ("bagged_knn", bagged_knn)
    ])

    estimators.append((f"knn_k{k}", pipe))

# soft voting
ensemble_knn = VotingClassifier(
    estimators=estimators,
    voting="soft",
    n_jobs=-1
)

print("Training Multi-K Ensemble KNN...")
ensemble_knn.fit(X_train, y_train)

y_pred_m12 = ensemble_knn.predict(X_test)
module12_acc = accuracy_score(y_test, y_pred_m12)

print("\n Module 12 Test Accuracy:", module12_acc)
print("\nClassification Report (Module 12):")
print(classification_report(y_test, y_pred_m12))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_m12))
module12_result = {
    "acc": module12_acc,
    "K_list": K_list,
    "status": "SUCCESS"
}

print("\nSaved module12_result =", module12_result)

===============================
 Module 12 – Multi-K Resampled Ensemble KNN
===============================

Using base parameters from Module 9:
{'metric': 'minkowski', 'n_neighbors': 28, 'p': 1, 'weights': 'distance'}

Multi-K ensemble will use K values: [15, 25, 35, 45]

Training Multi-K Ensemble KNN...

 Module 12 Test Accuracy: 0.659375

Classification Report (Module 12):
              precision    recall  f1-score   support

           3       0.00      0.00      0.00         2
           4       0.00      0.00      0.00        11
           5       0.72      0.74      0.73       136
           6       0.60      0.70      0.65       128
           7       0.67      0.50      0.57        40
           8       1.00      0.33      0.50         3

    accuracy                           0.66       320
   macro avg       0.50      0.38      0.41       320
weighted avg       0.64      0.66      0.64       320

Confusion Matrix:
[[  0   0   1   1   0   0]
 [  0   0   8   3   0   0]
 [  0   0 100  35   1   0]
 [  0   0  30  90   8   0]
 [  0   0   0  20  20   0]
 [  0   0   0   1   1   1]]

Saved module12_result = {'acc': 0.659375, 'K_list': [15, 25, 35, 45], 'status': 'SUCCESS'}

/opt/anaconda3/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/anaconda3/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/anaconda3/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [ ]:
# ============================================
# Module 13 — Final Comparison & Interpretation
# ============================================

print("\n================================")
print(" Module 13 – Final Comparison & Interpretation")
print("================================\n")

def safe_get(var_name, default=None):
    return globals()[var_name] if var_name in globals() else default

#  Test Accuracy
accuracies = {
    "Module 2 (Baseline KNN)": safe_get("module2_baseline_acc"),
    "Module 3 (Basic GridSearch)": safe_get("module3_acc"),
    "Module 4 (Advanced Tuning)": safe_get("module4_acc"),
    "Module 5 (StandardScaler)": safe_get("module5_acc"),
    "Module 6 (Feature Selection – ANOVA F-test)": safe_get("module6_acc"),
    "Module 7 (PCA Expansion)": safe_get("module7_acc"),
    "Module 8 (MI Selection)": safe_get("module8_acc"),
    "Module 9 (Polynomial Features)": safe_get("module9_acc"),
    "Module 10 (Feature Weighting)": safe_get("module10_acc"),
    "Module 11 (Noise Cleaning – NCR)": safe_get("module11_acc"),
    "Module 12 (Multi-K Ensemble KNN)": safe_get("module12_acc"),
}

accuracies = {k: v for k, v in accuracies.items() if v is not None}

print(" All Test Accuracies:\n")
for module, acc in accuracies.items():
    print(f"{module}: {acc:.4f}")

best_module = max(accuracies, key=accuracies.get)
best_acc = accuracies[best_module]

print("\n==============================")
print(" Final Decision")
print("==============================\n")

print(f"The best model comes from: **{best_module}**")
print(f"The highest Test Accuracy = **{best_acc:.4f}**\n")

explanation = {
    "Module 2": "No hyperparameter tuning or feature scaling was applied, resulting in poor performance.",
    "Module 3": "Basic GridSearch significantly improved performance, but did not achieve the optimal result.",
    "Module 4": "A larger search space was explored, but performance remained similar or slightly decreased.",
    "Module 5": "Introducing StandardScaler substantially improved generalization performance and served as the foundation for subsequent optimizations.",
    "Module 6": "ANOVA F-test–based feature selection did not yield meaningful improvements and was therefore rejected.",
    "Module 7": "PCA-based feature expansion provided only limited gains and failed to outperform the best model.",
    "Module 8": "Mutual Information–based feature selection retained the four most informative features and led to a significant performance improvement, achieving the best overall result.",
    "Module 9": "Polynomial feature expansion improved performance but did not surpass the MI-based selection approach.",
    "Module 10": "Feature weighting introduced additional noise and resulted in degraded performance.",
    "Module 11": "Noise cleaning via NCR severely distorted the data distribution, leading to reduced test performance and was therefore rejected.",
    "Module 12": "Multi-K ensemble KNN produced stable results but slightly underperformed compared to the MI-based model.",
}


print(" Why this module is best?\n")
print(explanation.get(best_module, ""))

================================
 Module 13 – Final Comparison & Interpretation
================================

 All Test Accuracies:

Module 3 (Basic GridSearch): 0.6125
Module 4 (Advanced Tuning): 0.6094
Module 5 (StandardScaler): 0.6562
Module 6 (Feature Selection – ANOVA F-test): 0.6500
Module 7 (PCA Expansion): 0.6531
Module 8 (MI Selection): 0.6719
Module 9 (Polynomial Features): 0.6656
Module 10 (Feature Weighting): 0.5531
Module 11 (Noise Cleaning – NCR): 0.5813
Module 12 (Multi-K Ensemble KNN): 0.6594

==============================
 Final Decision
==============================

The best model comes from: **Module 8 (MI Selection)**
The highest Test Accuracy = **0.6719**

 Why this module is best?

Exception ignored in: <function ResourceTracker.__del__ at 0x105139bc0>
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x104939bc0>
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x104365bc0>
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x1023d9bc0>
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x105565bc0>
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x1069f5bc0>
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x10e865bc0>
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x1037d1bc0>
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x105d65bc0>
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x105265bc0>
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x114121bc0>
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x119065bc0>
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x10a865bc0>
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes